const B77RS_LocalVariables = {};

/**
 * TODO: Remove this variable
 * Both versions will use same variable names and different system implementation
 *
 * @type {string}
 */
B77RS_LocalVariables.VERSION = 'B77RS';

B77RS_LocalVariables.SIM_RATE_MANAGER = {
	ACTIVATED: 'L:' + B77RS_LocalVariables.VERSION + '_SIM_RATE_MANAGER_ACTIVATED'
};

B77RS_LocalVariables.ADIRU = {
	STATE: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_STATE',
	SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_SWITCH_STATE',
	INIT_TIME: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_INIT_TIME',
	TIME_FOR_ALIGN: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_TIME_FOR_ALIGN',
	IS_INITED: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_IS_INITED',
	POSITION_SET: 'L:' + B77RS_LocalVariables.VERSION + '_ADIRU_POSITION_SET'
};

B77RS_LocalVariables.APU = {
	EGT: 'L:' + B77RS_LocalVariables.VERSION + '_APU_EGT',
	OIL_PRESS: 'L:' + B77RS_LocalVariables.VERSION + '_APU_OIL_PRESS',
	OIL_TEMP: 'L:' + B77RS_LocalVariables.VERSION + '_APU_OIL_TEMP',
	RPM: 'APU PCT RPM',
	SWITCH_STATE: 'A:APU SWITCH'
};

B77RS_LocalVariables.VNAV = {
	SPEED_RESTRICTION: {
		SPEED: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_SPEED_RESTRICTION_SPEED',
		ALTITUDE: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_SPEED_RESTRICTION_ALTITUDE',
		FMC_COMMAND_SPEED: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_SPEED_RESTRICTION_FMC_COMMAND_SPEED'
	},
	SELECTED_CLIMB_SPEED: {
		SPEED: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_SELECTED_CLIMB_SPEED_SPEED',
		FMC_COMMAND_SPEED: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_SELECTED_CLIMB_SPEED_FMC_COMMAND_SPEED'
	},
	CUSTOM_VNAV_CLIMB_ENABLED: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_CUSTOM_CLIMB_ENABLED',
	FMC_COMMAND_SPEED_TYPE: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_FMC_COMMAND_SPEED',
	CLIMB_LEVEL_OFF_ACTIVE: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_CLIMB_LEVEL_OFF_ACTIVE',
	CLIMB_LEVEL_OFF_AWAIT: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_CLIMB_LEVEL_OFF_AWAIT',
	DESCENT_LEVEL_OFF_ACTIVE: 'L:' + B77RS_LocalVariables.VERSION + '_VNAV_DESCENT_LEVEL_OFF_ACTIVE'
};

B77RS_LocalVariables.PRESSURIZATION = {
	PACKS: {
		L: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_PACK_L_SWITCH_STATE'
		},
		R: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_PACK_R_SWITCH_STATE'
		}
	},
	TRIM_AIR: {
		L: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_TRIMAIR_L_SWITCH_STATE'
		},
		R: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_TRIMAIR_R_SWITCH_STATE'
		}
	},
	FANS_LOWER: {
		SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_FANSLOWER_SWITCH_STATE'
	},
	RECIRC_UPPER: {
		SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_RECIRCUPPER_SWITCH_STATE'
	},
	COOLING_AFT: {
		SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_COOLINGAFT_SWITCH_STATE'
	},
	EQUIP_FWD: {
		SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PRESSURIZATION_EQUIPFWD_SWITCH_STATE'
	},
	TEMP: {
		CABIN: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PASSENGER_KNOB_TEMPERATURE_CABIN_SWITCH_STATE'
		},
		FLIGHT_DECK: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PASSENGER_KNOB_TEMPERATURE_FLIGHTDECK_SWITCH_STATE'
		},
		CARGO: {
			SWITCH_STATE: 'L:' + B77RS_LocalVariables.VERSION + '_PASSENGER_KNOB_TEMPERATURE_CARGO_SWITCH_STATE'
		}
	}

};
